// Code generated by a template
// Project: KnifeHub
// https://github.com/yiyungent/KnifeHub
// Author: yiyun <yiyungent@gmail.com>
// LastUpadteTime: 2023-11-12 12:36:15

using DataAnalysisPlugin.Domain.Entities;
using DataAnalysisPlugin.Repositories.EFCore.Interface;
using DataAnalysisPlugin.Services.EFCore.Core;
using DataAnalysisPlugin.Services.EFCore.Interface;

namespace DataAnalysisPlugin.Services.EFCore.Implement
{
    public partial class SimpleTimeTrackerCsvService : BaseService<SimpleTimeTrackerCsvEntity>, ISimpleTimeTrackerCsvService
    {
        private readonly ISimpleTimeTrackerCsvRepository _repository;
        public SimpleTimeTrackerCsvService(ISimpleTimeTrackerCsvRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
