// Code generated by a template
// Project: KnifeHub
// https://github.com/yiyungent/KnifeHub
// Author: yiyun <yiyungent@gmail.com>
// LastUpadteTime: 2023-11-12 12:38:57

using DataAnalysisPlugin.Domain.Entities;
using DataAnalysisPlugin.Services.EFCore.Core;

namespace DataAnalysisPlugin.Services.EFCore.Interface
{
    public partial interface ISimpleTimeTrackerCsvService : IService<SimpleTimeTrackerCsvEntity>
    { }
}
