// Code generated by a template
// Project: KnifeHub
// https://github.com/yiyungent/KnifeHub
// Author: yiyun <yiyungent@gmail.com>
// LastUpadteTime: 2023-11-12 12:28:34

using DataAnalysisPlugin.Domain.Entities;
using DataAnalysisPlugin.Repositories.EFCore.Core;

namespace DataAnalysisPlugin.Repositories.EFCore.Interface
{
    public partial interface ISimpleTimeTrackerCsvRepository : IRepository<SimpleTimeTrackerCsvEntity>
    { }
}
