// Code generated by a template
// Project: KnifeHub
// https://github.com/yiyungent/KnifeHub
// Author: yiyun <yiyungent@gmail.com>
// LastUpadteTime: 2023-11-12 12:29:35

using DataAnalysisPlugin.Domain.Entities;
using DataAnalysisPlugin.Repositories.EFCore.Core;
using DataAnalysisPlugin.Repositories.EFCore.Interface;

namespace DataAnalysisPlugin.Repositories.EFCore.Implement
{
    public partial class SimpleTimeTrackerCsvRepository : BaseRepository<SimpleTimeTrackerCsvEntity>, ISimpleTimeTrackerCsvRepository
    {
        private readonly EFCoreDbContext _context;

        public SimpleTimeTrackerCsvRepository(EFCoreDbContext context) : base(context)
        {
            this._context = context;
        }
    }
}
